on:
  push:
    branches:
      - src-pages


jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: src-pages
            fetch-depth: 10
            submodules: true

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/samidb.xyz/assets/css

      - name: Compile main.css from main.scss
        uses: gha-utilities/sass-build@v0.4.3
        with:
          source: |
            _scss/colors.scss
            _scss/fonts.scss
            _scss/main.scss
            _scss/components/_index.scss
            _scss/components/buttons.scss
            _scss/components/misctext.scss
            _scss/components/navbar.scss
          destination: |
            tmp/samidb.xyz/assets/css/colors.css
            tmp/samidb.xyz/assets/css/fonts.css
            tmp/samidb.xyz/assets/css/main.css
            tmp/samidb.xyz/assets/css/components/_index.css
            tmp/samidb.xyz/assets/css/components/buttons.css
            tmp/samidb.xyz/assets/css/components/misctext.css
            tmp/samidb.xyz/assets/css/components/navbar.css

      - name: Checkout destination Git branch
        uses: actions/checkout@v2
        with:
            ref: pr-pages
            fetch-depth: 1

      - name: Move compiled CSS to path within pr-pages branch
        run: mv /tmp/samidb.xyz/assets/css assets/

      - name: Add and Commit changes to pr-pages branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add assets/css/*
          git commit -m 'Updates compiled CSS files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: pr-pages

      - name: Initialize Pull Request
        uses: gha-utilities/init-pull-request@v0.0.4
        with:
          pull_request_token: ${{ secrets.GITHUB_TOKEN }}
          head: pr-pages
          base: gh-pages
          title: 'Updates site files from latest Actions build'
          body: >
            Perhaps a multi-line description
            about latest features and such.
